/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Vision;

namespace RosSharp.RosBridgeClient.MessageTypes.HriRobotArm
{
    public class RecordRequest : Message
    {
        public override string RosMessageName => "hri_robot_arm/Record";

        public Header header { get; set; }
        public BoundingBox3D bbox { get; set; }

        public RecordRequest()
        {
            this.header = new Header();
            this.bbox = new BoundingBox3D();
        }

        public RecordRequest(Header header, BoundingBox3D bbox)
        {
            this.header = header;
            this.bbox = bbox;
        }
    }
}
