/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class BoundingBox2D : Message
    {
        public override string RosMessageName => "vision_msgs/BoundingBox2D";

        //  A 2D bounding box that can be rotated about its center.
        //  All dimensions are in pixels, but represented using floating-point
        //    values to allow sub-pixel precision. If an exact pixel crop is required
        //    for a rotated bounding box, it can be calculated using Bresenham's line
        //    algorithm.
        //  The 2D position (in pixels) and orientation of the bounding box center.
        public Pose2D center { get; set; }
        //  The size (in pixels) of the bounding box surrounding the object relative
        //    to the pose of its center.
        public double size_x { get; set; }
        public double size_y { get; set; }

        public BoundingBox2D()
        {
            this.center = new Pose2D();
            this.size_x = 0.0;
            this.size_y = 0.0;
        }

        public BoundingBox2D(Pose2D center, double size_x, double size_y)
        {
            this.center = center;
            this.size_x = size_x;
            this.size_y = size_y;
        }
    }
}
