/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class BoundingBox3D : Message
    {
        public override string RosMessageName => "vision_msgs/BoundingBox3D";

        //  A 3D bounding box that can be positioned and rotated about its center (6 DOF)
        //  Dimensions of this box are in meters, and as such, it may be migrated to
        //    another package, such as geometry_msgs, in the future.
        //  The 3D position and orientation of the bounding box center
        public Pose center { get; set; }
        //  The size of the bounding box, in meters, surrounding the object's center
        //    pose.
        public Vector3 size { get; set; }

        public BoundingBox3D()
        {
            this.center = new Pose();
            this.size = new Vector3();
        }

        public BoundingBox3D(Pose center, Vector3 size)
        {
            this.center = center;
            this.size = size;
        }
    }
}
