/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class Detection2DArray : Message
    {
        public override string RosMessageName => "vision_msgs/Detection2DArray";

        //  A list of 2D detections, for a multi-object 2D detector.
        public Header header { get; set; }
        //  A list of the detected proposals. A multi-proposal detector might generate
        //    this list with many candidate detections generated from a single input.
        public Detection2D[] detections { get; set; }

        public Detection2DArray()
        {
            this.header = new Header();
            this.detections = new Detection2D[0];
        }

        public Detection2DArray(Header header, Detection2D[] detections)
        {
            this.header = header;
            this.detections = detections;
        }
    }
}
