/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class ObjectHypothesis : Message
    {
        public override string RosMessageName => "vision_msgs/ObjectHypothesis";

        //  An object hypothesis that contains no position information.
        //  The unique numeric ID of object detected. To get additional information about
        //    this ID, such as its human-readable name, listeners should perform a lookup
        //    in a metadata database. See vision_msgs/VisionInfo.msg for more detail.
        public long id { get; set; }
        //  The probability or confidence value of the detected object. By convention,
        //    this value should lie in the range [0-1].
        public double score { get; set; }

        public ObjectHypothesis()
        {
            this.id = 0;
            this.score = 0.0;
        }

        public ObjectHypothesis(long id, double score)
        {
            this.id = id;
            this.score = score;
        }
    }
}
