/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class ObjectHypothesisWithPose : Message
    {
        public override string RosMessageName => "vision_msgs/ObjectHypothesisWithPose";

        //  An object hypothesis that contains position information.
        //  The unique numeric ID of object detected. To get additional information about
        //    this ID, such as its human-readable name, listeners should perform a lookup
        //    in a metadata database. See vision_msgs/VisionInfo.msg for more detail.
        public long id { get; set; }
        //  The probability or confidence value of the detected object. By convention,
        //    this value should lie in the range [0-1].
        public double score { get; set; }
        //  The 6D pose of the object hypothesis. This pose should be
        //    defined as the pose of some fixed reference point on the object, such a
        //    the geometric center of the bounding box or the center of mass of the
        //    object.
        //  Note that this pose is not stamped; frame information can be defined by
        //    parent messages.
        //  Also note that different classes predicted for the same input data may have
        //    different predicted 6D poses.
        public PoseWithCovariance pose { get; set; }

        public ObjectHypothesisWithPose()
        {
            this.id = 0;
            this.score = 0.0;
            this.pose = new PoseWithCovariance();
        }

        public ObjectHypothesisWithPose(long id, double score, PoseWithCovariance pose)
        {
            this.id = id;
            this.score = score;
            this.pose = pose;
        }
    }
}
