/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.HriRobotArm
{
    public class RecordResult : Message
    {
        public override string RosMessageName => "hri_robot_arm/RecordResult";

        // result
        public bool success { get; set; }

        public RecordResult()
        {
            this.success = false;
        }

        public RecordResult(bool success)
        {
            this.success = success;
        }
    }
}
