/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.HriRobotArm
{
    public class RecordActionResult : ActionResult<RecordResult>
    {
        public override string RosMessageName => "hri_robot_arm/RecordActionResult";

        public RecordActionResult() : base()
        {
            this.result = new RecordResult();
        }

        public RecordActionResult(Header header, GoalStatus status, RecordResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
