/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.HriRobotArm
{
    public class RecordActionGoal : ActionGoal<RecordGoal>
    {
        public override string RosMessageName => "hri_robot_arm/RecordActionGoal";

        public RecordActionGoal() : base()
        {
            this.goal = new RecordGoal();
        }

        public RecordActionGoal(Header header, GoalID goal_id, RecordGoal goal) : base(header, goal_id)
        {
            this.goal = goal;
        }
    }
}
