/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.HriRobotArm
{
    public class RecordAction : Action<RecordActionGoal, RecordActionResult, RecordActionFeedback, RecordGoal, RecordResult, RecordFeedback>
    {
        public override string RosMessageName => "hri_robot_arm/RecordAction";

        public RecordAction() : base()
        {
            this.action_goal = new RecordActionGoal();
            this.action_result = new RecordActionResult();
            this.action_feedback = new RecordActionFeedback();
        }

    }
}
